version: "3"
services:
  anaconda: # 任意の名前（ディレクトリ名 + dev がコンテナ名となります）
    build:
      context: .
      dockerfile: Dockerfile
    image: anaconda
    ports:
    - "8080:8888"
    volumes:
    - .:/workdir