version: "3.3"
services:
  cppdev:
    build:
      context: .
      dockerfile: Dockerfile
    image: cpp
    container_name: cpp
    volumes:
      - type: bind
        source: .
        target: /cpp
    stdin_open: true
    tty: true
    working_dir: /cpp/src/build